export const diskList = [
    {   id:1, 
        title: 'hate crew deathroll', 
        band: 'children of bodom', 
        category:'trash metal', 
        date: 2003,
        price: 15, 
        front: './src/assets/img/ChB-HateCrewDeathroll-Front.jpg', 
        back: './src/assets/img/ChB-HateCrewDeathroll-Back.jpg', 
        disk: './src/assets/img/ChB-HateCrewDeathroll-Disk.jpg', 
        stock: 4, 
        comment: 'El álbum destaca por su combinación de elementos de thrash metal y death metal melódico, con riffs de guitarra más potentes y una estructura de canciones más accesible que en trabajos anteriores. La producción es nítida y contundente, permitiendo que cada instrumento brille, especialmente los virtuosos solos de guitarra y teclado de Alexi Laiho.'
    },
    {   id:2, 
        title: 'somewhere out in space', 
        band: 'gamma ray', 
        category:'power metal',
        date: 1997, 
        price: 17, 
        front: './src/assets/img/GR-SomewhereOutInSpace-Front.jpg', 
        back: './src/assets/img/GR-SomewhereOutInSpace-Back.jpg', 
        disk: './src/assets/img/GR-SomewhereOutInSpace-Disk.jpg', 
        stock: 6, 
        comment: 'Es considerado uno de los álbumes más importantes y representativos del género, destacando por su temática espacial y la energía que transmite su música. El disco marca un punto de inflexión en la banda, consolidando la formación más longeva de Gamma Ray y estableciendo un nuevo estándar de calidad en su sonido.'
    },
    {   id:3, 
        title: 'and thou shalt trust the seer', 
        band: 'haggard', 
        category:'metal sinfónico',
        date: 1997, 
        price: 12, 
        front: './src/assets/img/Hag-AndThouShaltTrustTheSeer-Front.jpg', 
        back: './src/assets/img/Hag-AndThouShaltTrustTheSeer-Back.jpg', 
        disk: './src/assets/img/Hag-AndThouShaltTrustTheSeer-Disk.jpg', 
        stock: 3, 
        comment: 'El disco se destaca por su mezcla única de elementos de metal, música clásica y medieval, con letras inspiradas en la figura de Nostradamus y la peste negra. La obra es considerada un hito en la carrera de Haggard, estableciendo su sonido característico y su enfoque en la narrativa histórica y conceptual.'
    },
    {   id:4, 
        title: 'crimson thunder', 
        band: 'hammer fall', 
        category:'power metal',
        date: 2002, 
        price: 13, 
        front: './src/assets/img/Ham-CrimsonThunder-Front.jpg', 
        back: './src/assets/img/Ham-CrimsonThunder-Back.jpg', 
        disk: './src/assets/img/Ham-CrimsonThunder-Disk.jpg', 
        stock: 7, 
        comment: 'Es conocido por su sonido clásico de power metal, con letras épicas y melodías pegadizas. El álbum fue producido por Charlie Bauerfeind y cuenta con la portada de Samwise Didier. Destaca por canciones como "Hearts on Fire", que tuvo video musical, y "Hearts on Fire", que se convirtió en un himno para muchos fans.'
    },
    {   id:5, 
        title: 'guerrero del arco iris', 
        band: 'rata blanca', 
        category:'hard rock',
        date: 1991, 
        price: 11, 
        front: './src/assets/img/RB-GuerreroDelArcoIris-Front.jpg', 
        back: './src/assets/img/RB-GuerreroDelArcoIris-Back.jpg', 
        disk: './src/assets/img/RB-GuerreroDelArcoIris-Disk.jpg', 
        stock: 2, 
        comment: 'El disco es conocido por su sonido potente y virtuoso, característico de la banda, y por sus letras que abordan temas de conciencia ambiental y crítica social, inspiradas en una profecía indígena sobre un guerrero que vendrá a salvar la Tierra.'
    },
    {   id:6, 
        title: 'Rebirth', 
        band: 'angra', 
        category:'power metal',
        date: 2001, 
        price: 13, 
        front: './src/assets/img/An-Rebirth-Front.jpg', 
        back: './src/assets/img/An-Rebirth-Back.jpg', 
        disk: './src/assets/img/An-Rebirth-Disk.jpg', 
        stock: 5, 
        comment: 'Es un álbum clave en su discografía, marcando un "renacimiento" (de ahí el título) tras la salida de tres miembros clave, incluyendo al vocalista Andre Matos. El álbum presenta a nuevos integrantes: Edu Falaschi en la voz, Felipe Andreoli en el bajo y Aquiles Priester en la batería. "Rebirth" es aclamado por su sonido potente y melódico, con una producción a cargo de Dennis Ward, y es considerado uno de los mejores discos de la banda, representando una nueva era para Angra.'
    },
    {   id:7, 
        title: 'brave new world', 
        band: 'iron maiden', 
        category:'heavy metal',
        date: 2000, 
        price: 18, 
        front: './src/assets/img/IM-BraveNewWorld-Front.jpg', 
        back: './src/assets/img/IM-BraveNewWorld-Back.jpg', 
        disk: './src/assets/img/IM-BraveNewWorld-Disk.jpg', 
        stock: 9, 
        comment: 'Marcó el regreso de Bruce Dickinson y Adrian Smith a la banda, generando gran expectativa. El álbum, inspirado en la novela de Aldous Huxley, es considerado un regreso triunfal de la banda a su mejor forma, con canciones destacadas como "The Wicker Man" y "Brave New World"'
    },
    {   id:8, 
        title: 'gaia epilogo', 
        band: 'mago de oz', 
        category:'hard rock',
        date: 2010, 
        price: 9, 
        front: './src/assets/img/MO-GaiaEpilogo-Front.jpg', 
        back: './src/assets/img/MO-GaiaEpilogo-Back.jpg', 
        disk: './src/assets/img/MO-GaiaEpilogo-Disk.jpg', 
        stock: 3, 
        comment: 'es un álbum recopilatorio de Mägo de Oz que incluye canciones que quedaron fuera de la trilogía "Gaia", así como algunas regrabaciones y remasterizaciones. Musicalmente, presenta un sonido más oscuro que los álbumes anteriores, con guitarras distorsionadas y una orquesta que acompaña las letras de contenido oscuro.'
    },
    {   id:9, 
        title: 'the black albun', 
        band: 'metallica', 
        category:'heavy metal',
        date: 1991, 
        price: 12, 
        front: './src/assets/img/Me-TheBlackAlbum-Front.jpg', 
        back: './src/assets/img/Me-TheBlackAlbum-Back.jpg', 
        disk: './src/assets/img/Me-TheBlackAlbum-Disk.jpg', 
        stock: 3, 
        comment: 'Este trabajo es un hito en la historia del heavy metal, marcando un cambio significativo en el sonido de la banda hacia un enfoque más accesible y comercial, sin perder su potencia. El álbum, lanzado en 1991, presenta canciones más cortas y melódicas, con riffs potentes y baladas icónicas como "Nothing Else Matters" y "Enter Sandman", que le abrieron las puertas a un público más amplio.'
    },
    {   id:10, 
        title: 'angel fall first', 
        band: 'nightwish', 
        category:'gotic metal',
        date: 1997, 
        price: 10, 
        front: './src/assets/img/Ni-AngelFallFirst-Front.jpg', 
        back: './src/assets/img/Ni-AngelFallFirst-Back.jpg', 
        disk: './src/assets/img/Ni-AngelFallFirst-Disk.jpg', 
        stock: 7, 
        comment: 'El disco muestra un sonido que mezcla power metal con elementos góticos, folk y clásicos, con un enfoque en la atmósfera y la narrativa. Aunque no fue tan exitoso como sus álbumes posteriores, este disco es importante porque marca el inicio de la banda y presenta las primeras composiciones de Tuomas Holopainen con Tarja Turunen en las voces, además de algunas canciones con voces masculinas por Tuomas.'
    }
];